config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :zweets
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "zweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_many :zweets
  def to_s
    "#{name} @#{pseudo}"
  end
end

app/models/zweet.rb
class Zweet < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to zweets_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :name, :pseudo, :photo, :description ])
    end
end

app/controllers/zweets_controller.rb
class ZweetsController < ApplicationController
  before_action :set_zweet, only: %i[ show edit update destroy ]

  # GET /zweets or /zweets.json
  def index
    @zweets = Zweet.all
  end

  # GET /zweets/1 or /zweets/1.json
  def show
  end

  # GET /zweets/new
  def new
    @zweet = Zweet.new
  end

  # GET /zweets/1/edit
  def edit
  end

  # POST /zweets or /zweets.json
  def create
    @zweet = Zweet.new(zweet_params)
    if @zweet.save
      redirect_to zweets_path, notice: 'Zweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /zweets/1 or /zweets/1.json
  def update
    respond_to do |format|
      if @zweet.update(zweet_params)
        format.html { redirect_to @zweet, notice: "Zweet was successfully updated." }
        format.json { render :show, status: :ok, location: @zweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @zweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zweets/1 or /zweets/1.json
  def destroy
    @zweet.destroy!

    respond_to do |format|
      format.html { redirect_to zweets_path, status: :see_other, notice: "Zweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zweet
      @zweet = Zweet.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def zweet_params
      params.expect(zweet: [ :content, :image, :user_id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zweets_helper.rb
module ZweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Zweeter" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: "Nom", label_html: { class: 'custom-label' } %>
    <%= f.input :pseudo, label: "Pseudo", label_html: { class: 'custom-label' } %>
    <%= f.input :photo, label: "URL photo de profil", label_html: { class: 'custom-label' } %>
    <%= f.input :description, label: "Description", label_html: { class: 'custom-label' } %>
    <%= f.input :verified, as: :boolean, label: "Verified", label_html: { class: 'custom-label' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary text-white' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Pseudo:</strong>
    <%= user.pseudo %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= user.photo %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= user.description %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Modification utilisateur" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Voir ce profil", @user %> |
  <%= link_to "Retour aux profils", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>
<div class="container mt-4">
  <div class="row">
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Voir ce profil", user %>
    </p>
  <% end %>
</div>
</div>
<%= link_to "Nouveau profil", new_user_path %>
</div>

app/views/users/new.html.erb
<% content_for :title, "New user" %>
<div class="container mt-4">
<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card">
      <div class="card-header">
        <h2>Nouveau profil</h2>
      </div>
      <div class="card-body">
        <%= render "form", user: @user %>
      </div>
      <div class="card-footer text-right">
        <%= link_to "◀︎ Retour à la création du Zweet", new_zweet_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Modifier ce profil", edit_user_path(@user) %> |
  <%= link_to "Retour au profils", users_path %>

  <%= button_to "Supprimer ce profil", @user, method: :delete %>
</div>

app/views/zweets/_form.html.erb
<%= simple_form_for(@zweet) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <p>Pour vous créer un nouveau profil -> <%= link_to "Cliquez ici !",new_user_path %> </p>
    <%= f.input :content %>
    <%= f.input :image %>
  </div>

  <%= f.button :submit, class: "btn btn-success text-white" %>
  <%= link_to "Retour aux Zweets", zweets_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/zweets/_zweet.html.erb
<style>
  .card {
    background-color: rgb(36, 36, 36) !important; 
    color: #fff !important;
    border: none; 
    border-radius: 10px; 
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); 
    font-family: 'Roboto', sans-serif;
  }

  .card-body {
    padding: 20px;
    text-align: left;
  }

  .card-text {
    margin-bottom: 15px;
  }

  .card-text strong {
    color: grey;
  }

  .img-fluid {
    border-radius: 10px;
  }
</style>

<div class="container text-center my-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div id="<%= dom_id zweet %>" class="card shadow-sm">
        <div class="card-body text-start">
          <p class="card-text">
            <% if zweet.user.photo.present? %>
              <span class="user-photo-badge" style="margin-right: 5px;">
          <img src="<%= zweet.user.photo %>" alt="User photo" class="rounded-circle" style="width: 35px; height: 35px;">
              </span>
            <% end %>
            <%= zweet.user.name %> 
            <% username, _domain = zweet.user.pseudo.split('@', 2) %> 
            <strong>@<%= username %></strong>
            <% if zweet.user.verified? %>
              <%= image_tag "verified.svg", class: "verified-badge", style: "width: 20px; height: 20px;" %>
            <% end %>
          </p>
          
          <p class="card-text mt-3">
            <%= zweet.content %>
          </p>
        </div>
        <div class="zweet-image justfiy-content-center">
          <% if zweet.image.present? %>
            <p class="card-image" style="position: relative; display: flex; justify-content: center;">
              <img src="<%= zweet.image %>" class="img-fluid" alt="image" 
                style="width: 100%; aspect-ratio: 1/1; object-fit: cover; border-radius: 10px;">
            </p>

          <% end %>
          <small style="position: absolute; bottom: 0; right: 5px; color: grey;">
                n°<%= zweet.id %>
          </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/zweets/edit.html.erb
<% content_for :title, "Editing zweet" %>
<div class="container my-4">
<h1>Modifier le zweet</h1>

<%= render "form", zweet: @zweet %>

<br>
</div>

app/views/zweets/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Zweets" %>

<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <div class="d-flex flex-column">
              <div class="order-0 text-left" style="width: 100%;">
                <%= image_tag 'imagelogo.svg', class: "img-fluid" %>
              </div>
                <div class="row my-4">
    <div class="col text-center">
      <h1 class="display-4 text-md-left text-center">Bienvenue sur Zweeter</h1>
      <p class="lead">Partagez vos pensées avec le monde entier de façon anonyme ; cliquez sur "New Zweet" et choisissez ou créez un profil. Attention, pour l'instant, les images peuvent seulement être importées via des liens.</p>
    </div>
  </div>
            </div>
            <div style="position: relative; left: 50%; transform: translateX(-50%);">
              <div class="d-flex justify-content-center mb-5">
                <%= link_to "New zweet", new_zweet_path, class: "btn btn-dark" %>
              </div>
            </div>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-8 text-center">
  <h1>Zweets Récents</h1>
  <p>Twitter mais avec un Z</p>
<div id="zweets">
  <% @zweets.order(created_at: :desc).each do |zweet| %>
    <%= render zweet %>
    <!-- <p>
      <%= link_to edit_zweet_path(zweet), class: "btn btn-outline-secondary mt-4" do %>
        <%= image_tag "edit.svg" %>
      <% end %>
    </p> -->
  <% end %>
</div>
</div>

app/views/zweets/new.html.erb
<% content_for :title, "New user" %>
<div class="container mt-4">
<div class="row justify-content-center">
    <div class="col-md-8">
    <div class="card">
        <div class="card-header">
            <h2>Nouveau Zweet</h2>
        </div>
        <div class="card-body">
            <%= render "form", zweet: @zweet %>
        </div>
    </div>
    </div>
</div>
</div>

app/views/zweets/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card mt-4">
        <div class="card-header">
          <h1>Zweet</h1>
        </div>
        <div class="card-body">
          <p><%= @zweet.content %></p>
          <p class="text-muted"><%= @zweet.created_at.strftime("%B %d, %Y %H:%M") %></p>
        </div>
        <div class="card-footer text-right">
          <%= link_to "Edit this zweet", edit_zweet_path(@zweet), class: "btn btn-warning" %>
          <%= link_to "Back to zweets", zweets_path, class: "btn btn-secondary" %>
          <%= button_to "Destroy this zweet", @zweet, method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>